// ref: https://www.reddit.com/r/adventofcode/comments/189q9wv/comment/kbsrno0/?utm_source=share&utm_medium=web2x&context=3
export default `.......5......
..7*..*.......
...*13*.......
.......15.....`
